name: HuuuLaa
permalink: :year/:month/:day/:title
baseurl: HuuuLaa.github.io

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2017
now: 2020
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : 270180394@qq.com
  github : HuuuLaa
  twitter : 

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Diary: "/diary"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
